import type { Theme } from "./schema";

export function buildFlutterTheme(theme: Theme): string {
  const { meta, tokens } = theme;
  const dark = tokens.colorsDark ?? tokens.colors;

  const dart = `import 'package:flutter/material.dart';

/// ${meta.name}
/// Generated by ThemeForge BYOK
/// ${meta.createdAt}

// ── Light Theme ──
class _AppThemeLight {
  _AppThemeLight._();

  static const Color backgroundPrimary = Color(${hexToDartColor(tokens.colors.backgroundPrimary)});
  static const Color backgroundSecondary = Color(${hexToDartColor(tokens.colors.backgroundSecondary)});
  static const Color surface = Color(${hexToDartColor(tokens.colors.surface)});
  static const Color border = Color(${hexToDartColor(tokens.colors.border)});
  static const Color textPrimary = Color(${hexToDartColor(tokens.colors.textPrimary)});
  static const Color textSecondary = Color(${hexToDartColor(tokens.colors.textSecondary)});
  static const Color accent = Color(${hexToDartColor(tokens.colors.accent)});
  static const Color success = Color(${hexToDartColor(tokens.colors.success)});
  static const Color warning = Color(${hexToDartColor(tokens.colors.warning)});
  static const Color danger = Color(${hexToDartColor(tokens.colors.danger)});

  static const String displayFont = '${escapeDartString(tokens.typography.displayFont)}';
  static const String bodyFont = '${escapeDartString(tokens.typography.bodyFont)}';
  static const String monoFont = '${escapeDartString(tokens.typography.monoFont)}';

  static const double spacingXs = ${parseSpacing(tokens.spacing.xs)};
  static const double spacingSm = ${parseSpacing(tokens.spacing.sm)};
  static const double spacingMd = ${parseSpacing(tokens.spacing.md)};
  static const double spacingLg = ${parseSpacing(tokens.spacing.lg)};
  static const double spacingXl = ${parseSpacing(tokens.spacing.xl)};

  static const double radiusSm = ${parseSpacing(tokens.radius.sm)};
  static const double radiusMd = ${parseSpacing(tokens.radius.md)};
  static const double radiusLg = ${parseSpacing(tokens.radius.lg)};

  static const Duration durationFast = Duration(milliseconds: ${parseDuration(tokens.motion.durationFast)});
  static const Duration durationNormal = Duration(milliseconds: ${parseDuration(tokens.motion.durationNormal)});

  static ColorScheme get colorScheme => const ColorScheme(
        brightness: Brightness.light,
        primary: accent,
        onPrimary: textPrimary,
        secondary: surface,
        onSecondary: textPrimary,
        surface: backgroundSecondary,
        onSurface: textPrimary,
        error: danger,
        onError: textPrimary,
        outline: border,
      );

  static ThemeData get themeData => _buildThemeData(
        brightness: Brightness.light,
        colorScheme: colorScheme,
        backgroundPrimary: backgroundPrimary,
        backgroundSecondary: backgroundSecondary,
        surface: surface,
        border: border,
        textPrimary: textPrimary,
        textSecondary: textSecondary,
        accent: accent,
        displayFont: displayFont,
        bodyFont: bodyFont,
        letterSpacingDisplay: ${parseLetterSpacing(tokens.typography.letterSpacing.display)},
        letterSpacingLabel: ${parseLetterSpacing(tokens.typography.letterSpacing.label)},
        radiusMd: radiusMd,
        spacingMd: spacingMd,
        spacingSm: spacingSm,
      );
}

// ── Dark Theme ──
class _AppThemeDark {
  _AppThemeDark._();

  static const Color backgroundPrimary = Color(${hexToDartColor(dark.backgroundPrimary)});
  static const Color backgroundSecondary = Color(${hexToDartColor(dark.backgroundSecondary)});
  static const Color surface = Color(${hexToDartColor(dark.surface)});
  static const Color border = Color(${hexToDartColor(dark.border)});
  static const Color textPrimary = Color(${hexToDartColor(dark.textPrimary)});
  static const Color textSecondary = Color(${hexToDartColor(dark.textSecondary)});
  static const Color accent = Color(${hexToDartColor(dark.accent)});
  static const Color success = Color(${hexToDartColor(dark.success)});
  static const Color warning = Color(${hexToDartColor(dark.warning)});
  static const Color danger = Color(${hexToDartColor(dark.danger)});

  static const String displayFont = '${escapeDartString(tokens.typography.displayFont)}';
  static const String bodyFont = '${escapeDartString(tokens.typography.bodyFont)}';
  static const String monoFont = '${escapeDartString(tokens.typography.monoFont)}';

  static const double spacingXs = ${parseSpacing(tokens.spacing.xs)};
  static const double spacingSm = ${parseSpacing(tokens.spacing.sm)};
  static const double spacingMd = ${parseSpacing(tokens.spacing.md)};
  static const double spacingLg = ${parseSpacing(tokens.spacing.lg)};
  static const double spacingXl = ${parseSpacing(tokens.spacing.xl)};

  static const double radiusSm = ${parseSpacing(tokens.radius.sm)};
  static const double radiusMd = ${parseSpacing(tokens.radius.md)};
  static const double radiusLg = ${parseSpacing(tokens.radius.lg)};

  static const Duration durationFast = Duration(milliseconds: ${parseDuration(tokens.motion.durationFast)});
  static const Duration durationNormal = Duration(milliseconds: ${parseDuration(tokens.motion.durationNormal)});

  static ColorScheme get colorScheme => const ColorScheme(
        brightness: Brightness.dark,
        primary: accent,
        onPrimary: textPrimary,
        secondary: surface,
        onSecondary: textPrimary,
        surface: backgroundSecondary,
        onSurface: textPrimary,
        error: danger,
        onError: textPrimary,
        outline: border,
      );

  static ThemeData get themeData => _buildThemeData(
        brightness: Brightness.dark,
        colorScheme: colorScheme,
        backgroundPrimary: backgroundPrimary,
        backgroundSecondary: backgroundSecondary,
        surface: surface,
        border: border,
        textPrimary: textPrimary,
        textSecondary: textSecondary,
        accent: accent,
        displayFont: displayFont,
        bodyFont: bodyFont,
        letterSpacingDisplay: ${parseLetterSpacing(tokens.typography.letterSpacing.display)},
        letterSpacingLabel: ${parseLetterSpacing(tokens.typography.letterSpacing.label)},
        radiusMd: radiusMd,
        spacingMd: spacingMd,
        spacingSm: spacingSm,
      );
}

// ── Shared ThemeData Builder ──
ThemeData _buildThemeData({
  required Brightness brightness,
  required ColorScheme colorScheme,
  required Color backgroundPrimary,
  required Color backgroundSecondary,
  required Color surface,
  required Color border,
  required Color textPrimary,
  required Color textSecondary,
  required Color accent,
  required String displayFont,
  required String bodyFont,
  required double letterSpacingDisplay,
  required double letterSpacingLabel,
  required double radiusMd,
  required double spacingMd,
  required double spacingSm,
}) {
  return ThemeData(
    brightness: brightness,
    colorScheme: colorScheme,
    useMaterial3: true,
    scaffoldBackgroundColor: backgroundPrimary,
    fontFamily: bodyFont,
    textTheme: TextTheme(
      displayLarge: TextStyle(
        fontFamily: displayFont,
        fontSize: 32,
        fontWeight: FontWeight.w600,
        letterSpacing: letterSpacingDisplay,
        color: textPrimary,
      ),
      displayMedium: TextStyle(
        fontFamily: displayFont,
        fontSize: 28,
        fontWeight: FontWeight.w600,
        letterSpacing: letterSpacingDisplay,
        color: textPrimary,
      ),
      displaySmall: TextStyle(
        fontFamily: displayFont,
        fontSize: 24,
        fontWeight: FontWeight.w600,
        letterSpacing: letterSpacingDisplay,
        color: textPrimary,
      ),
      headlineLarge: TextStyle(
        fontFamily: displayFont,
        fontSize: 22,
        fontWeight: FontWeight.w600,
        color: textPrimary,
      ),
      headlineMedium: TextStyle(
        fontFamily: displayFont,
        fontSize: 20,
        fontWeight: FontWeight.w600,
        color: textPrimary,
      ),
      headlineSmall: TextStyle(
        fontFamily: displayFont,
        fontSize: 18,
        fontWeight: FontWeight.w600,
        color: textPrimary,
      ),
      titleLarge: TextStyle(
        fontFamily: bodyFont,
        fontSize: 16,
        fontWeight: FontWeight.w500,
        color: textPrimary,
      ),
      titleMedium: TextStyle(
        fontFamily: bodyFont,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        color: textPrimary,
      ),
      titleSmall: TextStyle(
        fontFamily: bodyFont,
        fontSize: 12,
        fontWeight: FontWeight.w500,
        color: textSecondary,
      ),
      bodyLarge: TextStyle(
        fontFamily: bodyFont,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        color: textPrimary,
      ),
      bodyMedium: TextStyle(
        fontFamily: bodyFont,
        fontSize: 14,
        fontWeight: FontWeight.w400,
        color: textPrimary,
      ),
      bodySmall: TextStyle(
        fontFamily: bodyFont,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        color: textSecondary,
      ),
      labelLarge: TextStyle(
        fontFamily: bodyFont,
        fontSize: 12,
        fontWeight: FontWeight.w500,
        letterSpacing: letterSpacingLabel,
        color: textSecondary,
      ),
      labelMedium: TextStyle(
        fontFamily: bodyFont,
        fontSize: 10,
        fontWeight: FontWeight.w500,
        letterSpacing: letterSpacingLabel,
        color: textSecondary,
      ),
      labelSmall: TextStyle(
        fontFamily: bodyFont,
        fontSize: 9,
        fontWeight: FontWeight.w500,
        letterSpacing: letterSpacingLabel,
        color: textSecondary,
      ),
    ),
    cardTheme: CardThemeData(
      color: surface,
      elevation: 0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        side: BorderSide(color: border),
      ),
    ),
    inputDecorationTheme: InputDecorationTheme(
      filled: true,
      fillColor: backgroundSecondary,
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        borderSide: BorderSide(color: border),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        borderSide: BorderSide(color: border),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(radiusMd),
        borderSide: BorderSide(color: accent),
      ),
    ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        backgroundColor: accent,
        foregroundColor: textPrimary,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(radiusMd),
        ),
        padding: EdgeInsets.symmetric(
          horizontal: spacingMd,
          vertical: spacingSm,
        ),
      ),
    ),
    outlinedButtonTheme: OutlinedButtonThemeData(
      style: OutlinedButton.styleFrom(
        foregroundColor: textPrimary,
        side: BorderSide(color: border),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(radiusMd),
        ),
        padding: EdgeInsets.symmetric(
          horizontal: spacingMd,
          vertical: spacingSm,
        ),
      ),
    ),
  );
}

// ── Public API ──
class AppTheme {
  AppTheme._();

  static ThemeData get lightThemeData => _AppThemeLight.themeData;
  static ThemeData get darkThemeData => _AppThemeDark.themeData;

  static ThemeData themeData(Brightness brightness) {
    return brightness == Brightness.dark ? darkThemeData : lightThemeData;
  }

  static ThemeData of(BuildContext context) {
    return themeData(MediaQuery.platformBrightnessOf(context));
  }
}
`;

  return dart;
}

function hexToDartColor(hex: string): string {
  const clean = hex.replace("#", "").trim();
  if (clean.length === 6) {
    return `0xFF${clean}`;
  }
  if (clean.length === 8) {
    return `0x${clean}`;
  }
  return `0xFF${clean}`;
}

function escapeDartString(str: string): string {
  return str.replace(/'/g, "\\'").replace(/\$/g, "\\$");
}

function parseSpacing(value: string): number {
  const match = value.match(/^(\d+(?:\.\d+)?)/);
  return match ? parseFloat(match[1]) : 0;
}

function parseDuration(value: string): number {
  const match = value.match(/^(\d+(?:\.\d+)?)/);
  return match ? parseFloat(match[1]) : 0;
}

function parseLetterSpacing(value: string): number {
  const match = value.match(/^(\d+(?:\.\d+)?)/);
  return match ? parseFloat(match[1]) : 0;
}
